repos:
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.2.1
    hooks:
      - id: ansible-lint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.4.1-1
    hooks:
      - id: shfmt
