version: "3"

services:
  ubuntu:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace:cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Tokyo
