- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/{{ item.name }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  loop:
    - { name: .zshrc, dest: ~/.zshrc }
    - { name: .zshenv, dest: ~/.zshenv }
    - { name: .vimrc, dest: ~/.vimrc }
    - { name: .czrc, dest: ~/.czrc }
    - { name: .gitconfig, dest: ~/.gitconfig }
