- name: Install zsh
  ansible.builtin.apt:
    name: zsh
    update_cache: true
  become: true

- name: Disable chsh authentication
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/chsh
    regexp: '.*pam_shells\.so'
    line: "auth       sufficient   pam_shells.so"
  become: true

- name: Change shell
  ansible.builtin.shell: "chsh -s $(which zsh)"
  register: chsh
  changed_when: chsh.rc != 0

- name: Enable chsh authentication
  ansible.builtin.lineinfile:
    dest: /etc/pam.d/chsh
    regexp: '.*pam_shells\.so'
    line: "auth       required   pam_shells.so"
  become: true
