- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install tools
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - starship
    - ripgrep
    - fd
    - bat
    - lsd
    - git-delta
    - dust

- name: Install fzf
  ansible.builtin.shell: $(brew --prefix)/opt/fzf/install
  register: fzf
  changed_when: fzf.rc != 0

- name: Template a file to ~/.zshenv
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/zsh/templates/{{ item }}.j2"
    dest: "~/{{ item }}"
    mode: "0644"
  loop:
    - .zshenv
    - .zshrc
