- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install tools
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - gh
    - gitui
    - pre-commit

- name: Copy dotfiles
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/roles/git/files/{{ item }}"
    dest: "~/{{ item }}"
    mode: "0644"
  loop:
    - .czrc
    - .gitconfig
