- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install tools
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - gh
    - gitui

- name: Install pre-commit
  ansible.builtin.command: pip3 install pre_commit
