- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install tools
  community.general.homebrew:
    name: "{{ item }}"
  loop:
    - jq
    - nkf
    - fzf
    - direnv
    - pgcli
    - packer
    - shellcheck
