- name: Check go
  ansible.builtin.stat:
    path: /usr/local/go
  register: go

- name: Unarchive go
  ansible.builtin.unarchive:
    src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: true
  become: true
  when: not go.stat.exists

- name: Install tools
  ansible.builtin.command: "go install {{ item }}"
  loop: "{{ go_packages }}"
  environment:
    GOROOT: /usr/local/go
    PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
  register: tools
  changed_when: tools.rc != 0
