- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: mac.yml
  when: ansible_os_family == "Darwin"

- name: Create symlink
  ansible.builtin.file:
    src: ~/go/bin/bazelisk
    dest: ~/go/bin/bazel
    state: link
