- name: Install volta
  ansible.builtin.shell: curl https://get.volta.sh | bash -s -- --skip-setup
  args:
    warn: false
  register: volta
  changed_when: volta.rc != 0

- name: Install node
  ansible.builtin.command: "volta install node@{{ node_version }}"
  register: node
  changed_when: node.rc != 0

- name: Install yarn
  ansible.builtin.command: volta install yarn
  register: yarn
  changed_when: yarn.rc != 0

- name: Install commitizen
  ansible.builtin.command: yarn global add commitizen cz-conventional-changelog-ja
  register: commitizen
  changed_when: commitizen.rc != 0
