- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: ppa:jonathonf/vim
  become: true

- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: latest
    update_cache: true
  become: true
