- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Create vim-plug directory
  ansible.builtin.file:
    path: ~/.vim/autoload
    state: directory
    mode: "0755"

- name: Download vim-plug
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
